FROM ruby:3.4-alpine

RUN apk update && \
    apk add --no-cache git build-base libxml2-dev libxslt-dev postgresql-dev yaml-dev postgresql-client tzdata bash vim vips-dev gcompat imagemagick && \
    cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime

ENV APP_ROOT /app
RUN mkdir $APP_ROOT
WORKDIR $APP_ROOT

ENV LANG=ja_JP.UTF-8 \
    BUNDLE_JOBS=4 \
    BUNDLE_RETRY=3 \
    EDITOR=vim
RUN gem update --system && \
    gem install --no-document bundler:2.7.2

RUN bundle config set force_ruby_platform true